<script setup lang="ts">
import type { LegalSection } from '~/composables/legal'

useSeoMeta({
  title: 'Terms of Use — Avo',
})

definePageMeta({
  width: 'narrow',
  back: { to: '/avo', label: 'Avo', icon: '/avo/icon.png' },
  footerLinks: [
    { to: '/avo', label: 'Avo' },
    { to: '/avo/privacy', label: 'Privacy' },
  ],
})

const sections: LegalSection[] = [
  {
    title: '1. Acceptance of These Terms',
    content:
      'These Terms of Use ("Terms") govern your access to and use of the Avo mobile application and the marketing pages at <strong>fortytwo.page/avo</strong> (collectively, "Avo" or the "Service"), operated by Fortytwo Apps ("we", "us", or "our"). By creating an account, downloading the app, or otherwise using the Service, you agree to these Terms and to our <a href="/avo/privacy" class="inline-link">Privacy Policy</a>. If you do not agree, do not use the Service.',
  },
  {
    title: '2. Important Health Disclaimer',
    callout: 'danger',
    content:
      '<strong>Avo is not a medical device and does not provide medical advice, diagnosis, or treatment.</strong> Avo provides general nutritional and educational information generated by an artificial intelligence model. It is not a substitute for the advice of a licensed physician, registered dietitian, pharmacist, or other qualified health professional.',
    list: [
      'AI-generated nutrition values (calories, macronutrients, micronutrients, glycemic index, warnings, recipe suggestions) are <strong>estimates</strong> and may be inaccurate, incomplete or out of date.',
      'You must <strong>independently verify</strong> any information before relying on it — particularly if you have a food allergy, intolerance, chronic illness, are pregnant or nursing, are under 18, or are taking medication that may interact with food.',
      'Avo does <strong>not</strong> replace allergen labels on packaged food, restaurant disclosures, or the judgement of a qualified clinician.',
      'Never disregard professional medical advice or delay seeking it because of something you read in Avo.',
      'If you think you are experiencing a medical emergency (including a suspected allergic reaction), <strong>stop using the app and contact your local emergency services immediately</strong>.',
    ],
    note: 'You use the Service at your own risk.',
  },
  {
    title: '3. Eligibility',
    list: [
      'You must be at least 13 years old to use Avo. If you are between 13 and 18 (or the age of majority where you live), you may only use Avo with the consent and supervision of a parent, guardian, or qualified health professional.',
      'The Service is not appropriate for, and is not intended for, users with active eating disorders or any condition where calorie- and weight-tracking could be harmful. If this applies to you, please consult a qualified clinician before using Avo.',
      'You may not use Avo where doing so would violate applicable law.',
    ],
  },
  {
    title: '4. Your Account',
    list: [
      'Authentication is performed through your chosen identity provider (currently Google; Apple Sign-In is planned). You are responsible for the security of the underlying provider account.',
      'You agree to provide accurate information during onboarding. Inaccurate body stats, allergies or condition information may produce unsafe AI output.',
      'You may not share, sell, or transfer your account. One account is for one natural person.',
      'You may delete your account at any time. See section 11.',
    ],
  },
  {
    title: '5. Subscriptions, Trial &amp; Billing',
    subsections: [
      {
        title: '5.1 Premium plan',
        content:
          "Avo offers a single premium subscription tier (currently <strong>$3.99 / month</strong>, with a <strong>3 days free trial</strong> for new subscribers). The free tier provides limited access (today's dashboard, a limited number of daily AI analyses).",
      },
      {
        title: '5.2 How billing works',
        list: [
          'All purchases and renewals are processed by Apple App Store or Google Play through their standard in-app purchase systems.',
          'Payment is charged to your Apple ID / Google Play account at confirmation of purchase.',
          'Unless cancelled at least 24 hours before the end of the current period, the subscription renews automatically at the then-current price.',
          'You can manage or cancel the subscription at any time from your Apple ID or Google Play subscription settings.',
          'Prices may change. We will give reasonable notice in-app before any price increase takes effect on your subscription.',
        ],
      },
      {
        title: '5.3 Refunds',
        content:
          'Refunds for App Store and Google Play purchases are issued at the discretion of Apple and Google according to their respective policies. We are not able to issue refunds directly for in-app purchases.',
      },
    ],
  },
  {
    title: '6. AI Output &amp; "As-Is" Service',
    list: [
      'Avo uses a large language model to generate nutrition analyses, warnings, recipes and swap suggestions.',
      'AI output is <strong>probabilistic</strong>. It may contain errors, omissions, hallucinated values, or stale information. Identical inputs may yield different outputs.',
      'The Service, including all AI output, is provided <strong>"as is" and "as available"</strong>, without warranties of any kind, whether express or implied — including warranties of merchantability, fitness for a particular purpose, accuracy, completeness, non-infringement, or uninterrupted availability.',
      'We do not warrant that Avo will be error-free, available without interruption, or that the AI provider will remain available.',
    ],
  },
  {
    title: '7. Acceptable Use',
    content: 'You agree not to:',
    list: [
      'Reverse engineer, decompile or attempt to extract the source code, prompts or model behaviour of the Service, except to the extent permitted by mandatory law.',
      'Use Avo to develop a competing product or to train another machine learning model.',
      'Submit content that is illegal, harmful, harassing, or violates the rights of others.',
      'Attempt to bypass subscription paywalls, rate limits, allergen warnings, or row-level security in our backend.',
      'Probe, scan, or test the vulnerability of the Service, or breach any security or authentication measures, without our written permission.',
      'Use the Service for any clinical, diagnostic, or professional dietetic purpose unless you are independently qualified to do so.',
    ],
  },
  {
    title: '8. User Content',
    content:
      'You retain ownership of the meal descriptions, profile data and other content you submit ("User Content"). By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free licence to process, store and transmit it solely to operate and provide the Service to you (including transmitting the necessary parts to the AI provider for analysis). We do not use your User Content to train AI models.',
  },
  {
    title: '9. Intellectual Property',
    content:
      'The Avo app, brand, code, design, prompts and documentation are owned by Fortytwo Apps and protected by intellectual property laws. Except for the limited licence to use the Service on your personal device, no rights are granted to you in our intellectual property under these Terms.',
  },
  {
    title: '10. Third-Party Services',
    content:
      'Avo relies on third-party services (including Supabase, Google, Apple and RevenueCat). Your use of those services may also be subject to their own terms. We are not responsible for the conduct or availability of third-party services.',
  },
  {
    title: '11. Suspension &amp; Termination',
    list: [
      'You may stop using Avo at any time and delete your account from the in-app profile screen, or by emailing us. Deletion removes your profile and meal logs from our active database; backups are overwritten on our retention schedule (see Privacy Policy).',
      'We may suspend or terminate your access if you breach these Terms, abuse the Service, or pose a risk to other users or to Fortytwo Apps.',
      'Provisions that by their nature should survive termination (including sections 2, 6, 9, 12, 13 and 16) will survive.',
    ],
  },
  {
    title: '12. Limitation of Liability',
    callout: 'mute',
    content: 'To the maximum extent permitted by applicable law:',
    list: [
      'In no event will Fortytwo Apps, its founders, employees or contractors be liable for any indirect, incidental, special, consequential, exemplary or punitive damages — including loss of profits, data, goodwill, health outcomes, or any other intangible loss — arising out of or relating to your use of, or inability to use, the Service.',
      'Our total aggregate liability for any claim arising out of or related to the Service is limited to the greater of (a) the amount you actually paid us for the Service in the twelve months preceding the event giving rise to the claim, or (b) ten US dollars (US$10).',
    ],
    note: 'Some jurisdictions do not allow limitations of liability for certain damages. In those jurisdictions our liability is limited to the maximum extent permitted by law.',
  },
  {
    title: '13. Indemnification',
    content:
      'You agree to indemnify and hold harmless Fortytwo Apps and its operators from any claim, demand, loss, or damages — including reasonable legal fees — arising out of your User Content, your use of the Service in violation of these Terms, or your violation of any law or the rights of a third party.',
  },
  {
    title: '14. Changes to the Service or These Terms',
    content:
      'We may modify the Service, including adding, changing or removing features, at any time. We may also update these Terms. Material changes will be reflected with an updated "Last updated" date at the top of this page and, where required by law, communicated to you in-app. Continued use of the Service after a change takes effect constitutes acceptance.',
  },
  {
    title: '15. Governing Law &amp; Disputes',
    content:
      'These Terms are governed by the laws of the Republic of Türkiye, without regard to conflict-of-laws rules. The courts and enforcement offices of Istanbul (Türkiye) have exclusive jurisdiction over any dispute arising out of or relating to these Terms or the Service, except where mandatory consumer-protection law in your country of residence grants you the right to bring a claim before a local court.',
  },
  {
    title: '16. Miscellaneous',
    list: [
      'If any provision of these Terms is held unenforceable, the remaining provisions remain in full effect.',
      'Our failure to enforce any right is not a waiver of that right.',
      'You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition or sale of assets.',
      'These Terms, together with the Privacy Policy, are the entire agreement between you and Fortytwo Apps regarding the Service.',
    ],
  },
  {
    title: '17. Contact',
    contact: true,
  },
]
</script>

<template>
  <LegalDocument
    title="Terms of Use"
    updated="May 18, 2026"
    app-name="Avo"
    :sections="sections"
  />
</template>
