<script setup lang="ts">
import type { LegalSection } from '~/composables/legal'

useSeoMeta({
  title: 'Terms of Service — Chibi Studio',
  description: 'Terms of Service for Chibi Studio.',
})

definePageMeta({
  back: { to: '/chibi', label: 'Chibi Studio' },
})

const sections: LegalSection[] = [
  {
    title: 'Introduction',
    content:
      'These Terms of Service ("Terms") govern your access to and use of the Chibi Studio mobile application ("App") made available by Fortytwo Apps ("we", "us", or "our"). Please read these Terms carefully. By downloading, installing, or using the App, you agree to be bound by these Terms. If you do not agree, do not use the App.',
  },
  {
    title: '01. Eligibility',
    content:
      'You must be at least 13 years old to use the App, or 16 years old if you are located in the European Economic Area. By using the App, you represent and warrant that you meet the applicable age requirement. If you are under 18, you confirm that you have obtained parental or guardian consent.',
  },
  {
    title: '02. Account Registration',
    content: 'Access to the App requires signing in with a Google account. You are responsible for:',
    list: [
      'Maintaining the security of your Google credentials.',
      'All activity that occurs under your account.',
      'Notifying us immediately at <a class="inline-link" href="mailto:info@fortytwo.page">info@fortytwo.page</a> if you suspect unauthorised use of your account.',
    ],
    note: 'We reserve the right to suspend or permanently terminate any account that violates these Terms, engages in fraudulent activity, or poses a risk to other users or the service.',
  },
  {
    title: '03. Tokens and In-App Purchases',
    content: 'The App operates on a token-based system. Tokens are required to generate chibi images.',
    subsections: [
      {
        title: 'Pricing',
        content:
          'Standard resolution generations cost 4 tokens; high-detail 2K generations cost 6 tokens. Pricing is subject to change with notice.',
      },
      {
        title: 'Purchasing tokens',
        content:
          'Token packages are available via in-app purchase, processed by Apple App Store or Google Play. All transactions are subject to the respective platform\'s payment terms.',
      },
      {
        title: 'No refunds',
        content:
          'All token purchases are final and non-refundable, except as required by applicable law or mandated by Apple or Google\'s refund policies.',
      },
      {
        title: 'No cash value',
        content:
          'Tokens have no monetary value outside the App. They cannot be transferred between accounts, sold, or redeemed for cash.',
      },
      {
        title: 'Expiry',
        content:
          'Tokens do not expire while your account remains active. Upon account deletion, any remaining tokens are forfeited.',
      },
    ],
  },
  {
    title: '04. User-Submitted Content',
    content: 'By uploading a photo to the App, you:',
    list: [
      'Confirm that you own the photo or have the right to use it for this purpose.',
      'Grant us a limited, non-exclusive, royalty-free licence to process the photo solely to generate your chibi image.',
      'Acknowledge that your original photo is not stored on our servers after the generation process completes.',
    ],
    note: 'You must not upload photos of other individuals without their explicit consent. You are solely responsible for any content you submit and for ensuring it does not violate applicable laws or third-party rights.',
  },
  {
    title: '05. AI-Generated Content',
    content: 'The chibi images produced by the App are generated by an AI model. By using the App, you understand and accept that:',
    list: [
      'AI outputs may vary in quality and accuracy and do not constitute a guarantee of any specific result.',
      'Generated images are provided for your personal, non-commercial use.',
      'You may share generated images on personal social media profiles with credit to Chibi Studio.',
      'Commercial use of generated images (e.g. merchandise, advertising, resale) requires prior written permission from us.',
    ],
  },
  {
    title: '06. Intellectual Property',
    content:
      'All rights, title, and interest in and to the App — including its design, code, branding, and content (excluding your uploaded photos) — are owned by or licensed to us and are protected by applicable intellectual property laws. Nothing in these Terms transfers any ownership rights in the App to you. You are granted a limited, revocable, non-exclusive, non-transferable licence to use the App solely for your personal, non-commercial purposes.',
  },
  {
    title: '07. Prohibited Conduct',
    content: 'You agree not to:',
    list: [
      'Upload photos depicting nudity, violence, hate speech, illegal activity, or any content that violates applicable laws.',
      'Upload photos of third parties without their consent, or generate content designed to harass or defame any individual.',
      'Attempt to reverse engineer, decompile, or otherwise extract source code from the App.',
      'Use automated tools, bots, or scripts to interact with the App or circumvent rate limits.',
      'Attempt to manipulate, exploit, or abuse the token system or purchase verification process.',
      'Interfere with or disrupt the App\'s infrastructure, servers, or networks.',
      'Use the App in any manner that could expose us to legal liability.',
    ],
    note: 'Violation of these prohibitions may result in immediate account termination and, where applicable, reporting to relevant authorities.',
  },
  {
    title: '08. Disclaimer of Warranties',
    content:
      'The App is provided on an "as is" and "as available" basis, without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the App will be uninterrupted, error-free, or free of viruses or other harmful components. AI-generated outputs are inherently variable; we make no guarantees regarding the quality, accuracy, or suitability of generated images.',
  },
  {
    title: '09. Limitation of Liability',
    content:
      'To the fullest extent permitted by applicable law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising out of or in connection with your use of or inability to use the App. Our total aggregate liability to you for all claims arising from or related to these Terms or the App shall not exceed the amount you paid us in the 12 months preceding the claim.',
  },
  {
    title: '10. Indemnification',
    content:
      'You agree to indemnify, defend, and hold harmless Fortytwo Apps and its affiliates, officers, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or relating to: (a) your use of the App; (b) your violation of these Terms; or (c) your infringement of any third-party rights.',
  },
  {
    title: '11. Termination',
    content:
      'You may stop using the App at any time and request account deletion by contacting us at <a class="inline-link" href="mailto:info@fortytwo.page">info@fortytwo.page</a>. We may suspend or terminate your access to the App at any time, with or without notice, for conduct that we believe violates these Terms or is otherwise harmful to other users, us, or third parties. Upon termination, your licence to use the App ceases immediately and any unused tokens are forfeited.',
  },
  {
    title: '12. Changes to These Terms',
    content:
      'We reserve the right to modify these Terms at any time. When we make material changes, we will update the "Last updated" date and notify you within the App. Your continued use of the App after the effective date of the revised Terms constitutes your acceptance of those changes.',
  },
  {
    title: '13. Governing Law and Disputes',
    content:
      'These Terms are governed by and construed in accordance with applicable law. Any dispute arising from these Terms or your use of the App that cannot be resolved informally shall be submitted to binding arbitration or a court of competent jurisdiction as required by local law. If you are an EU consumer, nothing in these Terms affects your rights under mandatory local consumer protection laws.',
  },
  {
    title: '14. Contact',
    contact: true,
  },
]
</script>

<template>
  <LegalDocument
    title="Terms of Service"
    updated="March 29, 2026"
    app-name="Chibi Studio"
    :sections="sections"
  />
</template>
